# 20 Realistic Fictional Indian Service Providers for COOP AI Seed Data

INITIAL_WORKERS = [
    {
        "worker_id": "WRK-1001",
        "name": "Rajesh Kumar",
        "email": "rajesh.plumber@coopai.demo",
        "phone": "+91 98765 43210",
        "city": "Bengaluru",
        "state": "Karnataka",
        "address": "Indiranagar 100ft Road, Bengaluru",
        "latitude": 12.9716,
        "longitude": 77.5946,
        "skills": ["Plumbing", "Appliance Repair", "Mason"],
        "years_experience": 8.5,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.9,
        "completed_jobs": 142,
        "current_workload": 1,
        "recent_jobs_count": 2,
        "service_area": "Indiranagar, Koramangala, Domlur",
        "languages": ["Kannada", "English", "Hindi"],
        "earnings": 42500.0,
        "profile_photo": "https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=400&auto=format&fit=crop&q=80",
        "id_type": "Aadhaar Card",
        "id_document_url": "https://example.com/demo-aadhaar.pdf",
        "certificate_url": "https://example.com/demo-plumbing-cert.pdf",
        "work_photos": [
            "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&auto=format&fit=crop&q=80"
        ],
        "bank_details": {"bank": "HDFC Bank", "account": "XXXXXX4829", "upi": "rajesh@okaxis"}
    },
    {
        "worker_id": "WRK-1002",
        "name": "Ananya Sundaram",
        "email": "ananya.electric@coopai.demo",
        "phone": "+91 98401 12345",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "address": "Anna Nagar 2nd Avenue, Chennai",
        "latitude": 13.0827,
        "longitude": 80.2707,
        "skills": ["Electrical", "AC Service", "Appliance Repair"],
        "years_experience": 6.0,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.8,
        "completed_jobs": 98,
        "current_workload": 0,
        "recent_jobs_count": 1,
        "service_area": "Anna Nagar, Shenoy Nagar, Kilpauk",
        "languages": ["Tamil", "English"],
        "earnings": 38900.0,
        "profile_photo": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
        "id_type": "Aadhaar Card",
        "id_document_url": "https://example.com/demo-id.pdf",
        "certificate_url": "https://example.com/demo-electric-cert.pdf",
        "bank_details": {"bank": "State Bank of India", "account": "XXXXXX1928", "upi": "ananya@sbi"}
    },
    {
        "worker_id": "WRK-1003",
        "name": "Suresh Reddy",
        "email": "suresh.carpenter@coopai.demo",
        "phone": "+91 97012 34567",
        "city": "Hyderabad",
        "state": "Telangana",
        "address": "Gachibowli Main Road, Hyderabad",
        "latitude": 17.4401,
        "longitude": 78.3489,
        "skills": ["Carpentry", "Furniture Assembly"],
        "years_experience": 11.0,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.95,
        "completed_jobs": 210,
        "current_workload": 2,
        "recent_jobs_count": 4,
        "service_area": "Gachibowli, Hitec City, Madhapur",
        "languages": ["Telugu", "Hindi", "English"],
        "earnings": 65400.0,
        "profile_photo": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
        "id_type": "PAN Card",
        "bank_details": {"bank": "ICICI Bank", "account": "XXXXXX9910", "upi": "suresh@icici"}
    },
    {
        "worker_id": "WRK-1004",
        "name": "Priya Patil",
        "email": "priya.cleaning@coopai.demo",
        "phone": "+91 98220 98765",
        "city": "Mumbai",
        "state": "Maharashtra",
        "address": "Andheri West, SV Road, Mumbai",
        "latitude": 19.1197,
        "longitude": 72.8464,
        "skills": ["Cleaning", "Gardening", "Painting"],
        "years_experience": 5.0,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.75,
        "completed_jobs": 84,
        "current_workload": 0,
        "recent_jobs_count": 1,
        "service_area": "Andheri, Juhu, Vile Parle",
        "languages": ["Marathi", "Hindi", "English"],
        "earnings": 31200.0,
        "profile_photo": "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=400&auto=format&fit=crop&q=80",
        "id_type": "Aadhaar Card",
        "bank_details": {"bank": "Axis Bank", "account": "XXXXXX3341", "upi": "priya@axis"}
    },
    {
        "worker_id": "WRK-1005",
        "name": "Amit Sharma",
        "email": "amit.acservice@coopai.demo",
        "phone": "+91 99100 54321",
        "city": "Delhi",
        "state": "Delhi",
        "address": "Connaught Place, New Delhi",
        "latitude": 28.6315,
        "longitude": 77.2167,
        "skills": ["AC Service", "Appliance Repair", "Electrical"],
        "years_experience": 9.0,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.88,
        "completed_jobs": 175,
        "current_workload": 1,
        "recent_jobs_count": 3,
        "service_area": "Connaught Place, Karol Bagh, Rajendra Nagar",
        "languages": ["Hindi", "English"],
        "earnings": 58000.0,
        "profile_photo": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
        "id_type": "Voter ID",
        "bank_details": {"bank": "Punjab National Bank", "account": "XXXXXX8812", "upi": "amit@pnb"}
    },
    {
        "worker_id": "WRK-1006",
        "name": "Vikram Deshmukh",
        "email": "vikram.painter@coopai.demo",
        "phone": "+91 98900 11223",
        "city": "Pune",
        "state": "Maharashtra",
        "address": "Kothrud Depot Road, Pune",
        "latitude": 18.5074,
        "longitude": 73.8077,
        "skills": ["Painting", "Cleaning", "Mason"],
        "years_experience": 7.0,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.7,
        "completed_jobs": 92,
        "current_workload": 0,
        "recent_jobs_count": 0,
        "service_area": "Kothrud, Erandwane, Deccan",
        "languages": ["Marathi", "Hindi"],
        "earnings": 34000.0,
        "profile_photo": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80",
        "id_type": "Aadhaar Card",
        "bank_details": {"bank": "Bank of Maharashtra", "account": "XXXXXX2019", "upi": "vikram@mahb"}
    },
    {
        "worker_id": "WRK-1007",
        "name": "Subhash Banerjee",
        "email": "subhash.tutor@coopai.demo",
        "phone": "+91 98300 77889",
        "city": "Kolkata",
        "state": "West Bengal",
        "address": "Salt Lake Sector 5, Kolkata",
        "latitude": 22.5726,
        "longitude": 88.4373,
        "skills": ["Tutoring", "Computer Repair"],
        "years_experience": 10.0,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.92,
        "completed_jobs": 130,
        "current_workload": 1,
        "recent_jobs_count": 2,
        "service_area": "Salt Lake, New Town, Lake Town",
        "languages": ["Bengali", "English", "Hindi"],
        "earnings": 49000.0,
        "profile_photo": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80",
        "id_type": "PAN Card",
        "bank_details": {"bank": "UCO Bank", "account": "XXXXXX7721", "upi": "subhash@uco"}
    },
    {
        "worker_id": "WRK-1008",
        "name": "Karthik Subramanian",
        "email": "karthik.plumber@coopai.demo",
        "phone": "+91 94440 88776",
        "city": "Coimbatore",
        "state": "Tamil Nadu",
        "address": "RS Puram DB Road, Coimbatore",
        "latitude": 11.0168,
        "longitude": 76.9558,
        "skills": ["Plumbing", "Electrical", "Gardening"],
        "years_experience": 6.5,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.85,
        "completed_jobs": 76,
        "current_workload": 0,
        "recent_jobs_count": 1,
        "service_area": "RS Puram, Saibaba Colony, Gandhipuram",
        "languages": ["Tamil", "English"],
        "earnings": 29800.0,
        "profile_photo": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
        "id_type": "Aadhaar Card",
        "bank_details": {"bank": "Indian Overseas Bank", "account": "XXXXXX5124", "upi": "karthik@iob"}
    },
    {
        "worker_id": "WRK-1009",
        "name": "Meenakshi Sundari",
        "email": "meenakshi.gardening@coopai.demo",
        "phone": "+91 94860 11224",
        "city": "Madurai",
        "state": "Tamil Nadu",
        "address": "KK Nagar West, Madurai",
        "latitude": 9.9252,
        "longitude": 78.1198,
        "skills": ["Gardening", "Cleaning", "Tutoring"],
        "years_experience": 4.5,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.9,
        "completed_jobs": 58,
        "current_workload": 0,
        "recent_jobs_count": 0,
        "service_area": "KK Nagar, Tallakulam, Anna Nagar",
        "languages": ["Tamil"],
        "earnings": 22100.0,
        "profile_photo": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80",
        "id_type": "Aadhaar Card",
        "bank_details": {"bank": "Canara Bank", "account": "XXXXXX9012", "upi": "meenakshi@canara"}
    },
    {
        "worker_id": "WRK-1010",
        "name": "Saravanan Velu",
        "email": "saravanan.mason@coopai.demo",
        "phone": "+91 97890 33445",
        "city": "Trichy",
        "state": "Tamil Nadu",
        "address": "Thillai Nagar 10th Cross, Trichy",
        "latitude": 10.7905,
        "longitude": 78.7047,
        "skills": ["Mason", "Carpentry", "Painting"],
        "years_experience": 12.0,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.82,
        "completed_jobs": 165,
        "current_workload": 1,
        "recent_jobs_count": 2,
        "service_area": "Thillai Nagar, Srirangam, Cantonment",
        "languages": ["Tamil", "English"],
        "earnings": 52000.0,
        "profile_photo": "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80",
        "id_type": "Aadhaar Card",
        "bank_details": {"bank": "Indian Bank", "account": "XXXXXX6643", "upi": "saravanan@indianbank"}
    },
    {
        "worker_id": "WRK-1011",
        "name": "Bhavesh Patel",
        "email": "bhavesh.electrician@coopai.demo",
        "phone": "+91 98980 44556",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "address": "Navrangpura CG Road, Ahmedabad",
        "latitude": 23.0225,
        "longitude": 72.5714,
        "skills": ["Electrical", "Appliance Repair"],
        "years_experience": 7.5,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.78,
        "completed_jobs": 112,
        "current_workload": 0,
        "recent_jobs_count": 1,
        "service_area": "Navrangpura, Satellite, Bodakdev",
        "languages": ["Gujarati", "Hindi", "English"],
        "earnings": 41000.0,
        "profile_photo": "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=400&auto=format&fit=crop&q=80",
        "id_type": "Aadhaar Card",
        "bank_details": {"bank": "Kotak Mahindra", "account": "XXXXXX1154", "upi": "bhavesh@kotak"}
    },
    {
        "worker_id": "WRK-1012",
        "name": "Deepak Gowda",
        "email": "deepak.plumbing@coopai.demo",
        "phone": "+91 99000 66778",
        "city": "Bengaluru",
        "state": "Karnataka",
        "address": "Whitefield Main Road, Bengaluru",
        "latitude": 12.9698,
        "longitude": 77.7499,
        "skills": ["Plumbing", "AC Service"],
        "years_experience": 5.5,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.88,
        "completed_jobs": 89,
        "current_workload": 0,
        "recent_jobs_count": 0,
        "service_area": "Whitefield, Marathahalli, Brookfield",
        "languages": ["Kannada", "Telugu", "Hindi", "English"],
        "earnings": 36500.0,
        "profile_photo": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
        "id_type": "Aadhaar Card",
        "bank_details": {"bank": "Syndicate Bank", "account": "XXXXXX4488", "upi": "deepak@syndicate"}
    },
    {
        "worker_id": "WRK-1013",
        "name": "Kavitha Natarajan",
        "email": "kavitha.cleaning@coopai.demo",
        "phone": "+91 98410 77665",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "address": "Velachery Bypass Road, Chennai",
        "latitude": 12.9759,
        "longitude": 80.2212,
        "skills": ["Cleaning", "Gardening"],
        "years_experience": 4.0,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.92,
        "completed_jobs": 72,
        "current_workload": 0,
        "recent_jobs_count": 1,
        "service_area": "Velachery, Adambakkam, Madipakkam",
        "languages": ["Tamil", "English"],
        "earnings": 27500.0,
        "profile_photo": "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80",
        "id_type": "Aadhaar Card",
        "bank_details": {"bank": "Federal Bank", "account": "XXXXXX9901", "upi": "kavitha@federal"}
    },
    {
        "worker_id": "WRK-1014",
        "name": "Rohan Naidu",
        "email": "rohan.newworker@coopai.demo",
        "phone": "+91 96111 22334",
        "city": "Bengaluru",
        "state": "Karnataka",
        "address": "HSR Layout Sector 1, Bengaluru",
        "latitude": 12.9121,
        "longitude": 77.6446,
        "skills": ["Plumbing", "Electrical"],
        "years_experience": 3.0,
        "availability": "OFFLINE",
        "verification_status": "PENDING",
        "identity_verified": False,
        "skill_verified": False,
        "document_verified": False,
        "experience_verified": False,
        "rating": 4.5,
        "completed_jobs": 0,
        "current_workload": 0,
        "recent_jobs_count": 0,
        "service_area": "HSR Layout, BTM Layout",
        "languages": ["Kannada", "Hindi"],
        "earnings": 0.0,
        "profile_photo": "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80",
        "id_type": "Aadhaar Card",
        "id_document_url": "https://example.com/pending-id.pdf",
        "certificate_url": "https://example.com/pending-cert.pdf",
        "bank_details": {"bank": "State Bank of India", "account": "XXXXXX5521", "upi": "rohan@sbi"}
    },
    {
        "worker_id": "WRK-1015",
        "name": "Sunita Verma",
        "email": "sunita.tutor@coopai.demo",
        "phone": "+91 98110 44332",
        "city": "Delhi",
        "state": "Delhi",
        "address": "South Extension Part 2, New Delhi",
        "latitude": 28.5684,
        "longitude": 77.2195,
        "skills": ["Tutoring"],
        "years_experience": 8.0,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.96,
        "completed_jobs": 150,
        "current_workload": 1,
        "recent_jobs_count": 2,
        "service_area": "South Ext, Lajpat Nagar, Defence Colony",
        "languages": ["Hindi", "English"],
        "earnings": 56000.0,
        "profile_photo": "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&auto=format&fit=crop&q=80",
        "id_type": "PAN Card",
        "bank_details": {"bank": "HDFC Bank", "account": "XXXXXX1234", "upi": "sunita@hdfc"}
    },
    {
        "worker_id": "WRK-1016",
        "name": "Manish Rao",
        "email": "manish.carpenter@coopai.demo",
        "phone": "+91 97400 99887",
        "city": "Bengaluru",
        "state": "Karnataka",
        "address": "Jayanagar 4th Block, Bengaluru",
        "latitude": 12.9250,
        "longitude": 77.5938,
        "skills": ["Carpentry", "Mason"],
        "years_experience": 9.5,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.87,
        "completed_jobs": 128,
        "current_workload": 0,
        "recent_jobs_count": 1,
        "service_area": "Jayanagar, JP Nagar, Banashankari",
        "languages": ["Kannada", "Telugu", "English"],
        "earnings": 48200.0,
        "profile_photo": "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?w=400&auto=format&fit=crop&q=80",
        "id_type": "Aadhaar Card",
        "bank_details": {"bank": "Union Bank of India", "account": "XXXXXX8876", "upi": "manish@unionbank"}
    },
    {
        "worker_id": "WRK-1017",
        "name": "Lakshmi Narayanan",
        "email": "lakshmi.applicant@coopai.demo",
        "phone": "+91 94430 22110",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "address": "T Nagar Usman Road, Chennai",
        "latitude": 13.0418,
        "longitude": 80.2341,
        "skills": ["Cleaning", "Gardening"],
        "years_experience": 2.5,
        "availability": "OFFLINE",
        "verification_status": "PENDING",
        "identity_verified": False,
        "skill_verified": False,
        "document_verified": False,
        "experience_verified": False,
        "rating": 4.3,
        "completed_jobs": 0,
        "current_workload": 0,
        "recent_jobs_count": 0,
        "service_area": "T Nagar, Kodambakkam",
        "languages": ["Tamil"],
        "earnings": 0.0,
        "profile_photo": "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&auto=format&fit=crop&q=80",
        "id_type": "Aadhaar Card",
        "bank_details": {"bank": "Indian Overseas Bank", "account": "XXXXXX4432", "upi": "lakshmi@iob"}
    },
    {
        "worker_id": "WRK-1018",
        "name": "Ganesh Kadam",
        "email": "ganesh.appliance@coopai.demo",
        "phone": "+91 98230 66554",
        "city": "Mumbai",
        "state": "Maharashtra",
        "address": "Dadar West, Ranade Road, Mumbai",
        "latitude": 19.0178,
        "longitude": 72.8478,
        "skills": ["Appliance Repair", "AC Service", "Electrical"],
        "years_experience": 10.0,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.91,
        "completed_jobs": 195,
        "current_workload": 1,
        "recent_jobs_count": 3,
        "service_area": "Dadar, Prabhadevi, Matunga",
        "languages": ["Marathi", "Hindi", "English"],
        "earnings": 61000.0,
        "profile_photo": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
        "id_type": "Aadhaar Card",
        "bank_details": {"bank": "State Bank of India", "account": "XXXXXX9081", "upi": "ganesh@sbi"}
    },
    {
        "worker_id": "WRK-1019",
        "name": "Vijay Shankar",
        "email": "vijay.plumber@coopai.demo",
        "phone": "+91 98402 33221",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "address": "Adyar LB Road, Chennai",
        "latitude": 13.0012,
        "longitude": 80.2565,
        "skills": ["Plumbing", "Appliance Repair"],
        "years_experience": 7.0,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.86,
        "completed_jobs": 115,
        "current_workload": 0,
        "recent_jobs_count": 1,
        "service_area": "Adyar, Besant Nagar, Thiruvanmiyur",
        "languages": ["Tamil", "English"],
        "earnings": 43800.0,
        "profile_photo": "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80",
        "id_type": "Aadhaar Card",
        "bank_details": {"bank": "City Union Bank", "account": "XXXXXX3110", "upi": "vijay@cub"}
    },
    {
        "worker_id": "WRK-1020",
        "name": "Nisha Malhotra",
        "email": "nisha.tutor@coopai.demo",
        "phone": "+91 98711 00998",
        "city": "Delhi",
        "state": "Delhi",
        "address": "Dwarka Sector 10, New Delhi",
        "latitude": 28.5833,
        "longitude": 77.0500,
        "skills": ["Tutoring", "Cleaning"],
        "years_experience": 6.0,
        "availability": "AVAILABLE",
        "verification_status": "APPROVED",
        "identity_verified": True,
        "skill_verified": True,
        "document_verified": True,
        "experience_verified": True,
        "rating": 4.89,
        "completed_jobs": 102,
        "current_workload": 0,
        "recent_jobs_count": 1,
        "service_area": "Dwarka Sector 6 to 12",
        "languages": ["Hindi", "English"],
        "earnings": 39500.0,
        "profile_photo": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
        "id_type": "Aadhaar Card",
        "bank_details": {"bank": "ICICI Bank", "account": "XXXXXX7741", "upi": "nisha@icici"}
    }
]
